export default [
    { id: 1, name: 'AFEGANISTÃO' },
    { id: 2, name: 'ACROTÍRI E DECELIA' },
    { id: 3, name: 'ÁFRICA DO SUL' },
    { id: 4, name: 'ALBÂNIA' },
    { id: 5, name: 'ALEMANHA' },
    { id: 6, name: 'AMERICAN SAMOA' },
    { id: 7, name: 'ANDORRA' },
    { id: 8, name: 'ANGOLA' },
    { id: 9, name: 'ANGUILLA' },
    { id: 10, name: 'ANTÍGUA E BARBUDA' },
    { id: 11, name: 'ANTILHAS NEERLANDESAS' },
    { id: 12, name: 'ARÁBIA SAUDITA' },
    { id: 13, name: 'ARGÉLIA' },
    { id: 14, name: 'ARGENTINA' },
    { id: 15, name: 'ARMÉNIA' },
    { id: 16, name: 'ARUBA' },
    { id: 17, name: 'AUSTRÁLIA' },
    { id: 18, name: 'ÁUSTRIA' },
    { id: 19, name: 'AZERBAIJÃO' },
    { id: 20, name: 'BAHAMAS' },
    { id: 21, name: 'BANGLADECHE' },
    { id: 22, name: 'BARBADOS' },
    { id: 23, name: 'BARÉM' },
    { id: 24, name: 'BASSAS DA ÍNDIA' },
    { id: 25, name: 'BÉLGICA' },
    { id: 26, name: 'BELIZE' },
    { id: 27, name: 'BENIM' },
    { id: 28, name: 'BERMUDAS' },
    { id: 29, name: 'BIELORRÚSSIA' },
    { id: 30, name: 'BOLÍVIA' },
    { id: 31, name: 'BÓSNIA E HERZEGOVINA' },
    { id: 32, name: 'BOTSUANA' },
    { id: 33, name: 'BRASIL' },
    { id: 34, name: 'BRUNEI DARUSSALAM' },
    { id: 35, name: 'BULGÁRIA' },
    { id: 36, name: 'BURQUINA FASO' },
    { id: 37, name: 'BURUNDI' },
    { id: 38, name: 'BUTÃO' },
    { id: 39, name: 'CABO VERDE' },
    { id: 40, name: 'CAMARÕES' },
    { id: 41, name: 'CAMBOJA' },
    { id: 42, name: 'CANADÁ' },
    { id: 43, name: 'CATAR' },
    { id: 44, name: 'CAZAQUISTÃO' },
    { id: 45, name: 'CENTRO-AFRICANA REPÚBLICA' },
    { id: 46, name: 'CHADE' },
    { id: 47, name: 'CHILE' },
    { id: 48, name: 'CHINA' },
    { id: 49, name: 'CHIPRE' },
    { id: 50, name: 'COLÔMBIA' },
    { id: 51, name: 'COMORES' },
    { id: 52, name: 'CONGO' },
    { id: 53, name: 'CONGO REPÚBLICA DEMOCRÁTICA' },
    { id: 54, name: 'COREIA DO NORTE' },
    { id: 55, name: 'COREIA DO SUL' },
    { id: 56, name: 'COSTA DO MARFIM' },
    { id: 57, name: 'COSTA RICA' },
    { id: 58, name: 'CROÁCIA' },
    { id: 59, name: 'CUBA' },
    { id: 60, name: 'DINAMARCA' },
    { id: 61, name: 'DOMÍNICA' },
    { id: 62, name: 'EGIPTO' },
    { id: 63, name: 'EMIRADOS ÁRABES UNIDOS' },
    { id: 64, name: 'EQUADOR' },
    { id: 65, name: 'ERITREIA' },
    { id: 66, name: 'ESLOVÁQUIA' },
    { id: 67, name: 'ESLOVÉNIA' },
    { id: 68, name: 'ESPANHA' },
    { id: 69, name: 'ESTADOS UNIDOS' },
    { id: 70, name: 'ESTÓNIA' },
    { id: 71, name: 'ETIÓPIA' },
    { id: 72, name: 'FAIXA DE GAZA' },
    { id: 73, name: 'FIJI' },
    { id: 74, name: 'FILIPINAS' },
    { id: 75, name: 'FINLÂNDIA' },
    { id: 76, name: 'FRANÇA' },
    { id: 77, name: 'GABÃO' },
    { id: 78, name: 'GÂMBIA' },
    { id: 79, name: 'GANA' },
    { id: 80, name: 'GEÓRGIA' },
    { id: 81, name: 'GIBRALTAR' },
    { id: 82, name: 'GRANADA' },
    { id: 83, name: 'GRÉCIA' },
    { id: 84, name: 'GRONELÂNDIA' },
    { id: 85, name: 'GUADALUPE' },
    { id: 86, name: 'GUAM' },
    { id: 87, name: 'GUATEMALA' },
    { id: 88, name: 'GUERNSEY' },
    { id: 89, name: 'GUIANA' },
    { id: 90, name: 'GUIANA FRANCESA' },
    { id: 91, name: 'GUINÉ' },
    { id: 92, name: 'GUINÉ EQUATORIAL' },
    { id: 93, name: 'GUINÉ-BISSAU' },
    { id: 94, name: 'HAITI' },
    { id: 95, name: 'HONDURAS' },
    { id: 96, name: 'HONG KONG' },
    { id: 97, name: 'HUNGRIA' },
    { id: 98, name: 'IÉMEN' },
    { id: 99, name: 'ILHA BOUVET' },
    { id: 100, name: 'ILHA CHRISTMAS' },
    { id: 101, name: 'ILHA DE CLIPPERTON' },
    { id: 102, name: 'ILHA DE JOÃO DA NOVA' },
    { id: 103, name: 'ILHA DE MAN' },
    { id: 104, name: 'ILHA DE NAVASSA' },
    { id: 105, name: 'ILHA EUROPA' },
    { id: 106, name: 'ILHA NORFOLK' },
    { id: 107, name: 'ILHA TROMELIN' },
    { id: 108, name: 'ILHAS ASHMORE E CARTIER' },
    { id: 109, name: 'ILHAS CAIMAN' },
    { id: 110, name: 'ILHAS COCOS (KEELING)' },
    { id: 111, name: 'ILHAS COOK' },
    { id: 112, name: 'ILHAS DO MAR DE CORAL' },
    { id: 113, name: 'ILHAS FALKLANDS (ILHAS MALVINAS)' },
    { id: 114, name: 'ILHAS FEROE' },
    { id: 115, name: 'ILHAS GEÓRGIA DO SUL E SANDWICH DO SUL' },
    { id: 116, name: 'ILHAS MARIANAS DO NORTE' },
    { id: 117, name: 'ILHAS MARSHALL' },
    { id: 118, name: 'ILHAS PARACEL' },
    { id: 119, name: 'ILHAS PITCAIRN' },
    { id: 120, name: 'ILHAS SALOMÃO' },
    { id: 121, name: 'ILHAS SPRATLY' },
    { id: 122, name: 'ILHAS VIRGENS AMERICANAS' },
    { id: 123, name: 'ILHAS VIRGENS BRITÂNICAS' },
    { id: 124, name: 'ÍNDIA' },
    { id: 125, name: 'INDONÉSIA' },
    { id: 126, name: 'IRÃO' },
    { id: 127, name: 'IRAQUE' },
    { id: 128, name: 'IRLANDA' },
    { id: 129, name: 'ISLÂNDIA' },
    { id: 130, name: 'ISRAEL' },
    { id: 131, name: 'ITÁLIA' },
    { id: 132, name: 'JAMAICA' },
    { id: 133, name: 'JAN MAYEN' },
    { id: 134, name: 'JAPÃO' },
    { id: 135, name: 'JERSEY' },
    { id: 136, name: 'JIBUTI' },
    { id: 137, name: 'JORDÂNIA' },
    { id: 138, name: 'KIRIBATI' },
    { id: 139, name: 'KOWEIT' },
    { id: 140, name: 'LAOS' },
    { id: 141, name: 'LESOTO' },
    { id: 142, name: 'LETÓNIA' },
    { id: 143, name: 'LÍBANO' },
    { id: 144, name: 'LIBÉRIA' },
    { id: 145, name: 'LÍBIA' },
    { id: 146, name: 'LISTENSTAINE' },
    { id: 147, name: 'LITUÂNIA' },
    { id: 148, name: 'LUXEMBURGO' },
    { id: 149, name: 'MACAU' },
    { id: 150, name: 'MACEDÓNIA' },
    { id: 151, name: 'MADAGÁSCAR' },
    { id: 152, name: 'MALÁSIA' },
    { id: 153, name: 'MALAVI' },
    { id: 154, name: 'MALDIVAS' },
    { id: 155, name: 'MALI' },
    { id: 156, name: 'MALTA' },
    { id: 157, name: 'MARROCOS' },
    { id: 158, name: 'MARTINICA' },
    { id: 159, name: 'MAURÍCIA' },
    { id: 160, name: 'MAURITÂNIA' },
    { id: 161, name: 'MAYOTTE' },
    { id: 162, name: 'MÉXICO' },
    { id: 163, name: 'MIANMAR' },
    { id: 164, name: 'MICRONÉSIA' },
    { id: 165, name: 'MOÇAMBIQUE' },
    { id: 166, name: 'MOLDÁVIA' },
    { id: 167, name: 'MÓNACO' },
    { id: 168, name: 'MONGÓLIA' },
    { id: 169, name: 'MONTENEGRO' },
    { id: 170, name: 'MONTSERRAT' },
    { id: 171, name: 'NAMÍBIA' },
    { id: 172, name: 'NAURU' },
    { id: 173, name: 'NEPAL' },
    { id: 174, name: 'NICARÁGUA' },
    { id: 175, name: 'NÍGER' },
    { id: 176, name: 'NIGÉRIA' },
    { id: 177, name: 'NIUE' },
    { id: 178, name: 'NORUEGA' },
    { id: 179, name: 'NOVA CALEDÓNIA' },
    { id: 180, name: 'NOVA ZELÂNDIA' },
    { id: 181, name: 'OMÃ' },
    { id: 182, name: 'PAÍSES BAIXOS' },
    { id: 183, name: 'PALAU' },
    { id: 184, name: 'PALESTINA' },
    { id: 185, name: 'PANAMÁ' },
    { id: 186, name: 'PAPUÁSIA-NOVA GUINÉ' },
    { id: 187, name: 'PAQUISTÃO' },
    { id: 188, name: 'PARAGUAI' },
    { id: 189, name: 'PERU' },
    { id: 190, name: 'POLINÉSIA FRANCESA' },
    { id: 191, name: 'POLÓNIA' },
    { id: 192, name: 'PORTO RICO' },
    { id: 193, name: 'PORTUGAL' },
    { id: 194, name: 'QUÉNIA' },
    { id: 195, name: 'QUIRGUIZISTÃO' },
    { id: 196, name: 'REINO UNIDO' },
    { id: 197, name: 'REPÚBLICA CHECA' },
    { id: 198, name: 'REPÚBLICA DOMINICANA' },
    { id: 199, name: 'ROMÉNIA' },
    { id: 200, name: 'RUANDA' },
    { id: 201, name: 'RÚSSIA' },
    { id: 202, name: 'SAHARA OCCIDENTAL' },
    { id: 203, name: 'SALVADOR' },
    { id: 204, name: 'SAMOA' },
    { id: 205, name: 'SANTA HELENA' },
    { id: 206, name: 'SANTA LÚCIA' },
    { id: 207, name: 'SANTA SÉ' },
    { id: 208, name: 'SÃO CRISTÓVÃO E NEVES' },
    { id: 209, name: 'SÃO MARINO' },
    { id: 210, name: 'SÃO PEDRO E MIQUELÃO' },
    { id: 211, name: 'SÃO TOMÉ E PRÍNCIPE' },
    { id: 212, name: 'SÃO VICENTE E GRANADINAS' },
    { id: 213, name: 'SEICHELES' },
    { id: 214, name: 'SENEGAL' },
    { id: 215, name: 'SERRA LEOA' },
    { id: 216, name: 'SÉRVIA' },
    { id: 217, name: 'SINGAPURA' },
    { id: 218, name: 'SÍRIA' },
    { id: 219, name: 'SOMÁLIA' },
    { id: 220, name: 'SRI LANCA' },
    { id: 221, name: 'SUAZILÂNDIA' },
    { id: 222, name: 'SUDÃO' },
    { id: 223, name: 'SUÉCIA' },
    { id: 224, name: 'SUÍÇA' },
    { id: 225, name: 'SURINAME' },
    { id: 226, name: 'SVALBARD' },
    { id: 227, name: 'TAILÂNDIA' },
    { id: 228, name: 'TAIWAN' },
    { id: 229, name: 'TAJIQUISTÃO' },
    { id: 230, name: 'TANZÂNIA' },
    { id: 231, name: 'TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO' },
    { id: 232, name: 'TERRITÓRIO DAS ILHAS HEARD E MCDONALD' },
    { id: 233, name: 'TIMOR-LESTE' },
    { id: 234, name: 'TOGO' },
    { id: 235, name: 'TOKELAU' },
    { id: 236, name: 'TONGA' },
    { id: 237, name: 'TRINDADE E TOBAGO' },
    { id: 238, name: 'TUNÍSIA' },
    { id: 239, name: 'TURKS E CAICOS' },
    { id: 240, name: 'TURQUEMENISTÃO' },
    { id: 241, name: 'TURQUIA' },
    { id: 242, name: 'TUVALU' },
    { id: 243, name: 'UCRÂNIA' },
    { id: 244, name: 'UGANDA' },
    { id: 245, name: 'URUGUAI' },
    { id: 246, name: 'USBEQUISTÃO' },
    { id: 247, name: 'VANUATU' },
    { id: 248, name: 'VENEZUELA' },
    { id: 249, name: 'VIETNAME' },
    { id: 250, name: 'WALLIS E FUTUNA' },
    { id: 251, name: 'ZÂMBIA' },
    { id: 252, name: 'ZIMBABUÉ' },
];
